# Generated by Django 4.0.5 on 2022-06-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('typeOfWork', models.CharField(blank=True, max_length=500, null=True)),
                ('numberOfPerson', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('equipment', models.CharField(blank=True, max_length=200, null=True)),
                ('toolRequired', models.CharField(blank=True, max_length=200, null=True)),
                ('workDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('ppeRequired', models.CharField(blank=True, max_length=200, null=True)),
                ('verifiyedByPerson1Flag', models.BooleanField(default=False, null=True)),
                ('newFlag', models.BooleanField(default=False, null=True)),
                ('oldFlag', models.BooleanField(default=False, null=True)),
                ('closeFlag', models.BooleanField(default=False, null=True)),
                ('completedFlag', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='issueAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userlocation')),
                ('userName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userlogin')),
                ('userRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_notification', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.formdata')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userlogin')),
            ],
        ),
        migrations.AddField(
            model_name='formdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userlocation'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='loggedPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.userlogin'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='PGPapi.userlogin'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to='PGPapi.userlogin'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='workingAgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGPapi.issueagency'),
        ),
    ]
